services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=pmsvaporcorp
      - POSTGRES_PASSWORD=ZmD5ua7ry5KY93i
      - POSTGRES_DB=pms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
        
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
